Repository vatesfr/xen-orchestra, pull requests merged in 2024-01, with the labels that each got.

#7278 fix(lite): typings errors when running yarn type-check
  @xen-orchestra/lite/CHANGELOG.md
  @xen-orchestra/lite/src/composables/fetch-stats.composable.ts
  @xen-orchestra/lite/src/composables/host-patches.composable.ts
  @xen-orchestra/lite/src/composables/multi-select.composable.ts
Labels: XO Lite

#7291 feat(lite): introduce PWA manifest
  @xen-orchestra/lite/CHANGELOG.md
  @xen-orchestra/lite/index.html
  @xen-orchestra/lite/public/favicon.svg
  @xen-orchestra/lite/public/manifest.webmanifest
Labels: XO Lite

#7280 feat(xo-web/pool/host): add warning if hosts don't have the same version
  CHANGELOG.unreleased.md
  packages/xo-web/src/common/intl/messages.js
  packages/xo-web/src/xo-app/home/host-item.js
  packages/xo-web/src/xo-app/home/pool-item.js
  packages/xo-web/src/xo-app/host/tab-general.js
  packages/xo-web/src/xo-app/index.js
  packages/xo-web/src/xo-app/pool/tab-general.js
Labels: Highlight

#7293 feat(xo-web/host): ask for confirmation to reboot the updated slave host if the master is not
  CHANGELOG.unreleased.md
  packages/xo-server/src/api/host.mjs
  packages/xo-web/src/common/intl/messages.js
  packages/xo-web/src/common/xo/index.js
Labels: Highlight

#7262 feat(xo-web,xo-server/tag): add colored tag
  CHANGELOG.unreleased.md
  packages/xo-server/src/api/tag.mjs
  packages/xo-server/src/models/tag.mjs
  packages/xo-server/src/xo-mixins/tags.mjs
  packages/xo-web/src/common/intl/locales/it.js
  packages/xo-web/src/common/intl/messages.js
  packages/xo-web/src/common/tags.js
  packages/xo-web/src/common/xo/index.js
  packages/xo-web/src/index.scss
Labels: Highlight

#7324 fix(xo-server/PIF): IPv4 reconfiguration only worked when mode was updated
  CHANGELOG.unreleased.md
  packages/xo-server/src/api/pif.mjs
Labels: type: bug :bug:

#7309 feat(xo6): introducing `@xen-orchestra/web`
  @xen-orchestra/lite/package.json
  @xen-orchestra/web-core/package.json
  @xen-orchestra/web/.npmignore
  @xen-orchestra/web/.vscode/extensions.json
  @xen-orchestra/web/README.md
  @xen-orchestra/web/env.d.ts
  @xen-orchestra/web/index.html
  @xen-orchestra/web/package.json
  @xen-orchestra/web/public/favicon.svg
  @xen-orchestra/web/src/App.vue
  @xen-orchestra/web/src/main.ts
  @xen-orchestra/web/tsconfig.app.json
  @xen-orchestra/web/tsconfig.json
  @xen-orchestra/web/tsconfig.node.json
  @xen-orchestra/web/vite.config.ts
  packages/xo-server/config.toml
  yarn.lock
Labels: XO Web 6

#7243 feat(xo-web/pool): ability to do a rolling pool reboot
  CHANGELOG.unreleased.md
  packages/xo-web/src/common/intl/messages.js
  packages/xo-web/src/common/xo/index.js
  packages/xo-web/src/common/xo/rolling-pool-reboot-modal/index.js
  packages/xo-web/src/icons.scss
  packages/xo-web/src/xo-app/pool/tab-advanced.js
Labels: Highlight

#7318 feat(xo6): setup file based router
  .eslintrc.js
  @xen-orchestra/web/package.json
  @xen-orchestra/web/src/App.vue
  @xen-orchestra/web/src/main.ts
  @xen-orchestra/web/src/pages/index.vue
  @xen-orchestra/web/tsconfig.app.json
  @xen-orchestra/web/typed-router.d.ts
  @xen-orchestra/web/vite.config.ts
  yarn.lock
Labels: XO Web 6
